import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

export const metadata = {
  title: "Jio Creative Labs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="max-w-[1920px] mx-auto overflow-hidden">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
